### PR TITLE
Preliminary support input text fields

### PR DESCRIPTION
**Pull request by akirk**
## Description
In an effort to support (contact) forms, I've been converting forms into JSON like this (which for now is put into the data attribute of a `core-import/plugin-placeholder` block):

```
[
  {
    type: 'text',
    label: 'Name (Required)',
    placeholder: '',
    required: true
  },
  {
    type: 'text',
    label: ' Email (Required)',
    placeholder: '',
    required: true
  },
  { type: 'text', label: 'Phone', placeholder: '', required: false },
  {
    type: 'date',
    label: 'date (required)',
    placeholder: '',
    required: true,
    dateFormat: 'MM/DD/YYYY',
    disabledDates: [],
    disabledDaysOfWeek: [],
    allowPastDates: true,
    allowFutureDates: true
  },
  {
    type: 'select',
    label: 'Time (required)',
    options: [
      { text: '11:30 AM', value: '11:30 AM', description: '11:30 AM' },
      { text: '12:00 PM', value: '12:00 PM', description: '12:00 PM' },
      { text: '12:30 PM', value: '12:30 PM', description: '12:30 PM' },
      { text: '1:00 PM', value: '1:00 PM', description: '1:00 PM' },
      { text: '1:30 PM', value: '1:30 PM', description: '1:30 PM' },
      { text: '2:00 PM', value: '2:00 PM', description: '2:00 PM' },
      { text: '7:00 PM', value: '7:00 PM', description: '7:00 PM' },
      { text: '7:30 PM', value: '7:30 PM', description: '7:30 PM' },
      { text: '8:00 PM', value: '8:00 PM', description: '8:00 PM' },
      { text: '8:30 PM', value: '8:30 PM', description: '8:30 PM' },
      { text: '9:00 PM', value: '9:00 PM', description: '9:00 PM' },
      { text: '9:30 PM', value: '9:30 PM', description: '9:30 PM' }
    ],
    required: true
  },
  {
    type: 'select',
    label: 'Party size(required)',
    options: [
      { text: '1 person', value: '1 person', description: '1 person' },
      { text: '2 people', value: '2 people', description: '2 people' },
      { text: '3 people', value: '3 people', description: '3 people' },
      { text: '4 people', value: '4 people', description: '4 people' },
      { text: '5 people', value: '5 people', description: '5 people' },
      { text: '6 people', value: '6 people', description: '6 people' },
      {
        text: 'Large Party',
        value: 'Large Party',
        description: 'Large Party'
      }
    ],
    required: true
  },
  {
    type: 'textarea',
    label: 'Special Request',
    placeholder: '',
    required: false
  },
  { type: 'submit', label: 'Submit' }
]

```

The idea is then to convert this to some sort of meta data and can be inserted as a plugin placeholder.

### CODE REVIEW

**Comment by akirk** [comment]
I had a first stab at a WXR version 1.3 that adds support for objects.

We now have a placeholder in the HTML like this:
```
<!-- wp:core-import/plugin-placeholder {"id":2} /-->
```

and then in the WXR an entry like this:
```
	<object>
		<id>2</id>
		<data:json><![CDATA[[{"type":"text","label":"Name (Required)","placeholder":"","required":true},{"type":"text","label":" Email (Required)","placeholder":"","required":true},{"type":"text","label":"Phone","placeholder":"","required":false},{"type":"date","label":"date (required)","placeholder":"","required":true,"dateFormat":"MM/DD/YYYY","disabledDates":[],"disabledDaysOfWeek":[],"allowPastDates":true,"allowFutureDates":true},{"type":"select","label":"Time (required)","options":[{"text":"11:30 AM","value":"11:30 AM","description":"11:30 AM"},{"text":"12:00 PM","value":"12:00 PM","description":"12:00 PM"},{"text":"12:30 PM","value":"12:30 PM","description":"12:30 PM"},{"text":"1:00 PM","value":"1:00 PM","description":"1:00 PM"},{"text":"1:30 PM","value":"1:30 PM","description":"1:30 PM"},{"text":"2:00 PM","value":"2:00 PM","description":"2:00 PM"},{"text":"7:00 PM","value":"7:00 PM","description":"7:00 PM"},{"text":"7:30 PM","value":"7:30 PM","description":"7:30 PM"},{"text":"8:00 PM","value":"8:00 PM","description":"8:00 PM"},{"text":"8:30 PM","value":"8:30 PM","description":"8:30 PM"},{"text":"9:00 PM","value":"9:00 PM","description":"9:00 PM"},{"text":"9:30 PM","value":"9:30 PM","description":"9:30 PM"}],"required":true},{"type":"select","label":"Party size(required)","options":[{"text":"1 person","value":"1 person","description":"1 person"},{"text":"2 people","value":"2 people","description":"2 people"},{"text":"3 people","value":"3 people","description":"3 people"},{"text":"4 people","value":"4 people","description":"4 people"},{"text":"5 people","value":"5 people","description":"5 people"},{"text":"6 people","value":"6 people","description":"6 people"},{"text":"Large Party","value":"Large Party","description":"Large Party"}],"required":true},{"type":"textarea","label":"Special Request","placeholder":"","required":false},{"type":"submit","label":"Submit"}]]]></data:json>
	</object>
```

Putting JSON into the XML is not optimal but it's very flexible. While it'd be a lot nicer to put the data into XML tags, I am afraid about having to standardize the XML schema for every new object type we want to support, plus each change and iteration would also require a new WXR version.

This is why I went for just putting the JSON into the XML as a first iteration step and discussion point.

**Comment by pento** [comment]
> Putting JSON into the XML is not optimal but it's very flexible. While it'd be a lot nicer to put the data into XML tags, I am afraid about having to standardize the XML schema for every new object type we want to support, plus each change and iteration would also require a new WXR version.

For the moment, I'm not concerned about us having an XML spec that we _must_ adhere to. Since there are only a few people working on this at the moment, it's easy to coordinate changes between us, and the benefits of being able to iterate quickly far outweigh any breakages that might occur.

At a later point, we'd certainly want to lock a spec down, since plugin devs would need to be certain of what data they'd be receiving. That's just something to keep in mind as we iterate, though, it's not something to worry about adhering to.

**Comment by akirk** [comment]
I have rebased this onto #51 and thus it now embeds XML like this for a contact form:
```
	<wp:object xmlns="http://wordpress.org/export/objects/contact-form/1.0/" id="1">
		<email/>
		<field type="text" label="Name (Required)" placeholder="" required/>
		<field type="text" label=" Email (Required)" placeholder="" required/>
		<field type="text" label="Phone" placeholder="" required="false"/>
		<field type="text" format="date" label="date (required)" placeholder="" required dateFormat="MM/DD/YYYY" disabledDates="" disabledDaysOfWeek="" allowPastDates allowFutureDates/>
		<field type="select" label="Time (required)" required>
			<option value="11:30 AM">11:30 AM</option>
			<option value="12:00 PM">12:00 PM</option>
			<option value="12:30 PM">12:30 PM</option>
			<option value="1:00 PM">1:00 PM</option>
			<option value="1:30 PM">1:30 PM</option>
			<option value="2:00 PM">2:00 PM</option>
			<option value="7:00 PM">7:00 PM</option>
			<option value="7:30 PM">7:30 PM</option>
			<option value="8:00 PM">8:00 PM</option>
			<option value="8:30 PM">8:30 PM</option>
			<option value="9:00 PM">9:00 PM</option>
			<option value="9:30 PM">9:30 PM</option>
		</field>
		<field type="select" label="Party size(required)" required>
			<option value="1 person">1 person</option>
			<option value="2 people">2 people</option>
			<option value="3 people">3 people</option>
			<option value="4 people">4 people</option>
			<option value="5 people">5 people</option>
			<option value="6 people">6 people</option>
			<option value="Large Party">Large Party</option>
		</field>
		<field type="textarea" label="Special Request" placeholder="" required="false"/>
		<field type="submit" label="Submit"/>
	</wp:object>
```

[It's still unclear to me](https://github.com/pento/free-as-in-speech/pull/51#discussion_r625049275) how to get the id assigned by the lib to match up with the Gutenberg block.

**Comment by akirk** [comment]
@pento Here is a test implementation of importing the data on the PHP side: https://github.com/WordPress/wordpress-importer/compare/master...akirk:try-wp-objects

**Comment by akirk** [comment]
Although this PR is still somewhat experimental, we'll merge this to main to reduce the levels of PRs waiting for merge.

**Pull request merged**
