### PR TITLE
Preliminary add FSE support

### PR DESCRIPTION
**Pull request by akirk**
## Description
This converts Wix's header and footer to the respective FSE blocks.

## How has this been tested?
With Rockfield

## Screenshots
Screenshot 2021-04-20 at 17 41 37

### CODE REVIEW

**Comment by akirk** [comment]
Currently I am stuck on getting the navigation block registered because I haven't been able to `process.env.GUTENBERG_PHASE` [to an integer of 2](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/index.js#L213), so in the screenshot above I've added the menu manually.

**Comment by pento** [comment]
> I haven't been able to `process.env.GUTENBERG_PHASE` [to an integer of 2](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/index.js?rgh-link-date=2021-04-20T15%3A45%3A34Z#L213)

Do you have the Gutenberg plugin installed and activated? I believe it's set to 2 there.

**Comment by akirk** [comment]
It works alright in a WordPress context but this is about serializing the block to the WXR, there is no ENV variable set, and if I set it though the command line it's a string and not an integer.

**Comment by pento** [comment]
Oh, I see. Does changing it [in our webpack](https://github.com/pento/free-as-in-speech/blob/8c8dceb5c7ac7bf3759efc1ed32551c46b5a16b1/webpack.config.js#L39) work?

**Comment by akirk** [comment]
For the extension maybe, for running in node not since we're not using webpack in that context. I'm looking into setting the variable directly at runtime.

**Comment by akirk** [comment]
Unfortunately:
```
process.env.GUTENBERG_PHASE = 2;
console.log( process.env.GUTENBERG_PHASE, typeof process.env.GUTENBERG_PHASE ); // 2 string
```

but the check in Gutenberg is:
```
export const __experimentalRegisterExperimentalCoreBlocks =
	process.env.GUTENBERG_PHASE === 2
```

**Comment by akirk** [comment]
No need to fake anything in the screenshot anymore, this is [how we now](https://github.com/pento/free-as-in-speech/pull/48/commits/c1358c50977826abafcc66d3792354c08bd5a328) generate the header+menu:
```
<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p><strong><a>Rockfield</a></strong>&nbsp; Award-winning Restaurant in Anytown</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:navigation {"orientation":"horizontal"} -->
<!-- wp:navigation-link {"label":"Home","url":"/home"} /-->

<!-- wp:navigation-link {"label":"Menu","url":"/menu"} -->
<!-- wp:navigation-link {"label":"Winter Menu","url":"/winter-menu"} /-->
<!-- /wp:navigation-link -->

<!-- wp:navigation-link {"label":"What's On","url":"/blog"} /-->

<!-- wp:navigation-link {"label":"Reservations","url":"/reservations"} /-->
<!-- /wp:navigation --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

Screenshot 2021-05-07 at 17 44 53

One caveat: if we specify the (wxr-internal) page id, it's not rewritten by the usual import methods, so the page id remains unchanged which causes a menu item to be [hidden because it's not published](https://github.com/WordPress/gutenberg/blob/b7714fee96933fffb536db1467ebd8acda88290c/packages/block-library/src/navigation-link/index.php#L114).

**Comment by akirk** [comment]
At the moment we're locking in the theme for which FSE is supported as `tt1-blocks` since this is how FSE works right now. The nice thing is that since we still export the menu as before, FSE is just an add-on if you happen to have that particular theme enabled. We'll have to see in a future version if we can remove the theme requirement.

**Comment by akirk** [comment]
We're moving ahead with merging this so that we can proceed with the conversion of the static-pages into a separate package in #52.

**Pull request merged**
