### PR TITLE
Adding site-parsers package

### PR DESCRIPTION
**Pull request by bogiii**
## Description

This PR introduces `gutenberg-for-node` and `site-parsers` packages. Static pages parser has been moved to the package and can now be consumed from the different projects.

- Created `site-parsers` package (for now, there is only wix)
- Exported `staticPagesParserWix` method dedicated Wix static pages parser
- Moved its dependency logic to the package as well (utils methods, component, and container mappers)
- Broke down the staticPagesParser into multiple smaller methods such as addHeaderPage, addFooterPage, convertMenu, etc.
- Created `gutenberg-for-node` package

## How has this been tested?

Manual testing, unit tests.

## Types of changes

New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by bogiii** [comment]
FYI @akirk ⬆️ 

Also, we can always rename the package or change the folder structure.

**Comment by akirk** [comment]
Sorry, the `try-fse` branch was deleted with the merge that caused this to be closed.

**Review by akirk — CHANGES_REQUESTED** [review]
The tests are currently failing, this would need to be changed + a cleanup. https://github.com/bogiii/free-as-in-speech/compare/add/parser-package...pento:add/parser-package-pr

Otherwise it looks and works. I think we can merge it after updating the PR description.

**Comment by akirk** [comment]
I found two more problems and fixed them in commits to the branch I mentioned above, could you pull them in (maybe via `cherry-pick`?)

**Review by akirk — APPROVED** [review]
Tests pass, previous test was fine! Let's merge!

**Pull request merged**
